#!/bin/bash
set -euo errexit

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

function exit_and_fail() {
   echo "❌ Test Failed! Found a markdown file with spelling errors."
   exit 1
}
trap exit_and_fail INT ERR

docker build -t misspell $SCRIPTPATH
docker run -i --rm -v $SCRIPTPATH/../../:/aeiq misspell /bin/bash -c 'find /aeiq/ -type f -name "*.md" -not -path "build" | grep -v "/build/" | xargs misspell -error -debug'
echo "✅ Markdown file spell check passed!"