#! /usr/bin/env bash

set -euo pipefail

TEST_SUITE_USED="$TEST_SUITE"_invalid_args_test

function test() {
  cmd=$1
  test_type=$2
  output_file="$OUTPUT_DIR"/"$test_type".tmp

  result=$($cmd >$output_file 2>&1 || echo "true")

  assert_value "$result" "true" $test_type
  is_resources_deleted "$(cat $output_file)" $test_type
}

test "$AEIQ_BIN --instance-types=$SUPPORTED_INSTANCE_TYPES --test-suite=non-existent-folder --target-utilization=50" "non_existent_test_suite_failure"
test "$AEIQ_BIN --instance-types=$SUPPORTED_INSTANCE_TYPES --test-suite=$TEST_SUITE_USED --target-utilization=30 --vpc=$VPC_WITHOUT_SUBNET" "vpc_without_subnet_failure"
test "$AEIQ_BIN --instance-types=$SUPPORTED_INSTANCE_TYPES --test-suite=$TEST_SUITE_USED --target-utilization=50 --vpc=vpc-123456789 --subnet=subnet-123456789" "invalid_vpc_and_subnet_failure"
test "$AEIQ_BIN --instance-types=$UNSUPPORTED_INSTANCE_TYPE_AMI,$UNSUPPORTED_INSTANCE_TYPE_AZ --test-suite=$TEST_SUITE_USED --target-utilization=50 --subnet=$SUBNET_ID" "no_supported_instance_types"

exit $EXIT_CODE_TO_RETURN
