#! /usr/bin/env bash

set -euo pipefail

CONFIG_FILE=$SCRIPTPATH/testdata/test-folder_timeout_with_unsupported_instance_types/target-util-80-args.json

function test() {
  cmd=$1
  instance_types=$2
  test_type=$3
  golden_file=$4
  output_file="$OUTPUT_DIR"/"$test_type".tmp

  $cmd <<< $'y\n0' >$output_file 2>&1

  result=$(cat $output_file)
  verify_result "$instance_types" "$result" $golden_file $test_type
  delete_bucket "$(grep -m 1 -o -E "qualifier-bucket-.{15}" $output_file)"
  is_resources_deleted "$result" $test_type
}

test "$AEIQ_BIN --instance-types=$SUPPORTED_INSTANCE_TYPES --test-suite=${TEST_SUITE}_no_optional_flags --target-utilization=95 --custom-script=$CUSTOM_SCRIPT" "$SUPPORTED_INSTANCE_TYPES" "no_optional_flags" "target_util_95.golden" & pids+=($!)
sleep 1
test "$AEIQ_BIN --config-file=$CONFIG_FILE --test-suite=${TEST_SUITE}_timeout_with_unsupported_instance_types --subnet=$SUBNET_ID --custom-script=$CUSTOM_SCRIPT" "$ALL_INSTANCE_TYPES" "timeout_with_unsupported_instance_types" "target_util_80_timeout.golden" & pids+=($!)

for pid in "${pids[@]}"; do
  wait $pid
done

exit $EXIT_CODE_TO_RETURN